---
- name: Launch instance
  ec2:
    region: "{{ aws_region }}"
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    count: "{{ ec2_exact_count }}"
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    assign_public_ip: no 
    group: "{{ ec2_group }}"
    volumes: "{{ ec2_root_volume }}"
    instance_tags: 
      Name: "{{ Server_name }}"
  register: ec2

- name: Add new host to our inventory.
  add_host: hostname={{inventory_hostname}} groupname=launched ansible_ssh_host={{ item.public_ip }} ansible_ssh_user=centos ansible_ssh_private_key_file=/home/inder/Downloads/aws.pem become=true become_user=root
  with_items: "{{ ec2.instances }}"
  register: newec2

- name: Wait for instance
  shell: sleep 60s

