---
- name: Install GitLab Dependencies
  yum: state=present name={{ item }}
  with_items:
    - openssh-server
    - openssh-clients
    - curl
    - policycoreutils

- name: Download GitLab repository
  get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh dest=~

- name: Install repository 
  command: /bin/bash ~/script.rpm.sh 
       
- name: Install GitLab
  yum: name=gitlab-ce state=present

- name: Copy SSL certificate
  copy:
    src: roles/gitlabec2/files/selfsigned.pem
    dest: /etc/pki/tls/certs/selfsigned.pem

- name: Fetch NFS instance facts
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ gitnfs_name }}"
  register: nfsec2

- name: Fetch the private ip of NFS instance
  set_fact:
    nfsip: "{{ item.private_ip_address }}"
  with_items:
    - "{{ nfsec2.instances }}"

- name: Add NFS endpoints in fstab
  lineinfile:
    dest: /etc/fstab
    line: "{{ nfsip }}:{{ item }}"
    state: present
  with_items:
    - "/var/opt/gitlab/git-data /var/opt/gitlab/git-data nfs4 defaults,soft,rsize=1048576,wsize=1048576,noatime,nobootwait,lookupcache=positive 0 2"

    - "/var/opt/gitlab/.ssh /var/opt/gitlab/.ssh nfs4 defaults,soft,rsize=1048576,wsize=1048576,noatime,nobootwait,lookupcache=positive 0 2"

    - "/var/opt/gitlab/gitlab-rails/uploads /var/opt/gitlab/gitlab-rails/uploads nfs4 defaults,soft,rsize=1048576,wsize=1048576,noatime,nobootwait,lookupcache=positive 0 2"

    - "/var/opt/gitlab/gitlab-rails/shared /var/opt/gitlab/gitlab-rails/shared nfs4 defaults,soft,rsize=1048576,wsize=1048576,noatime,nobootwait,lookupcache=positive 0 2"

    - "/var/opt/gitlab/gitlab-ci/builds /var/opt/gitlab/gitlab-ci/builds nfs4 defaults,soft,rsize=1048576,wsize=1048576,noatime,nobootwait,lookupcache=positive 0 2"

- name: Fetch RDS facts
  rds:
    region: "{{ aws_region }}"
    command: facts
    instance_name: "{{ rds_instance_name }}"
  register: rds_facts

- name: Get RDS endpoint
  set_fact:
    rdsendp: "{{ item.endpoint }}"
  with_items:
    - "{{ rds_facts.instance }}"

- name: Update gitlab config
  template:
    src: roles/gitlabec2/templates/gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb

- name: Re-configure GitLab
  command: /usr/bin/gitlab-ctl reconfigure

- name: Restart GitLab
  shell: gitlab-ctl restart



